name: Shows JS Action 
on:
  push:
    branches:
      - "master" 
  pull_request:
    branches:
      - "master"
    types: [closed, assigned, opened, reopened]
jobs:
  github-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: List items in the Directory
        run: |
          ls -a
          pwd
      - name: clones the Directory
        uses: actions/checkout@v1
      - name: List items in the Directory after Checkout
        run: |
          ls -a
          pwd
      - name: JS Action
        id: JS
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Santhosh
      - name: Output of JS Action
        run: echo "${{steps.JS.outputs.time}}"