name: Shows JS Action 
on: [push]
jobs:
  github-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: JS Action
        id: JS
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Santhosh
      - name: Output of JS Action
        run: echo "${{steps.JS.outputs.time}}""