name: node version
on: push
jobs:
  node-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [6,8,10]
        include:
          - os: ubuntu-latest
            node_version: 4
        exclude:
          - os: windows-latest
            node_version: 10 
      fail-fast: false # if false, without depending on success or failure it will contine the process
      max-parallel: 3 # Max number of parallel jobs
    steps:
      - name: Logs node version
        run: |
          node -v
      - name: Changing node version
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Logs node version after Changing
        run: |
          node -v