name: Shell Commands
on: [push]
jobs:
  linux-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echoing the name Santhosh
        run: echo "Hello World"
      - name: Print versions of Node
        shell: bash
        run: |
          node -v
          npm -v
  linux-windows-command:
      runs-on: windows-latest
      needs: ["linux-shell-command"]
      steps:
        - name: Prints Working Directory
          run: Get-Location
        - name: Changing Shell
          shell: bash
          run: pwd
  